"""empty message

Revision ID: 0d7adcb86230
Revises: f59ef22fdc8a
Create Date: 2019-03-29 05:44:45.602147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7adcb86230'
down_revision = 'f59ef22fdc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.Column('asked_by', sa.Integer(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=52), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=True),
    sa.Column('solvedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asked_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('status')
    op.drop_table('department')
    # ### end Alembic commands ###
