"""empty message

Revision ID: ae290ac65131
Revises: 
Create Date: 2019-02-19 19:22:24.010970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae290ac65131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('is_auth', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('violation_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_by', sa.Integer(), nullable=True),
    sa.Column('violation_on', sa.String(length=15), nullable=True),
    sa.Column('violation', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=140), nullable=True),
    sa.Column('violation_time', sa.DateTime(), nullable=True),
    sa.Column('acknowledge', sa.Boolean(), nullable=True),
    sa.Column('remarks_vio', sa.String(length=140), nullable=True),
    sa.Column('acknowledge_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['violation'], ['violation_list.id'], ),
    sa.ForeignKeyConstraint(['violation_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation')
    op.drop_table('violation_list')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
