"""empty message

Revision ID: d3b74c88ef46
Revises: 
Create Date: 2019-02-25 11:08:08.432078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b74c88ef46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severity_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=14), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('is_auth', sa.Boolean(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('violation_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation', sa.String(length=140), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['severity'], ['severity_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_by', sa.Integer(), nullable=True),
    sa.Column('violation_on', sa.Integer(), nullable=True),
    sa.Column('violation', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=140), nullable=True),
    sa.Column('violation_time', sa.DateTime(), nullable=True),
    sa.Column('acknowledge', sa.Boolean(), nullable=True),
    sa.Column('remarks_vio', sa.String(length=140), nullable=True),
    sa.Column('acknowledge_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['violation'], ['violation_list.id'], ),
    sa.ForeignKeyConstraint(['violation_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['violation_on'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('vio_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['vio_id'], ['violation.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('violation')
    op.drop_table('violation_list')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('severity_list')
    # ### end Alembic commands ###
