"""permission

Revision ID: efa67bf45c7a
Revises: 27dfe5eb4bed
Create Date: 2019-02-15 16:16:30.248282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa67bf45c7a'
down_revision = '27dfe5eb4bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('user', sa.Column('emp_id', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('is_auth', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'other')
    op.drop_column('user', 'is_auth')
    op.drop_column('user', 'emp_id')
    op.drop_column('user', 'designation')
    # ### end Alembic commands ###
